### ISSUE TITLE
support: having trouble getting started

### ISSUE THREAD

**Issue by jkitchin** [CoLRev-Environment/colrev#151]
# Support Question

I am having trouble getting started. I can run `colrev init`, and `colrev status`.

I tried `colrev search -a colrev.crossref:"https://search.crossref.org/?q=+microsourcing&from_ui=yes"` as the next step, following an example from: https://colrev.readthedocs.io/en/latest/manual/metadata_retrieval/search.html. It runs a while, and the output appears to be retrieving DOIs, e.g. I see output like

```
2023-04-08 13:46:09 [INFO]  retrieve 10.4028/P-FG0I9U
2023-04-08 13:46:09 [INFO]  retrieve 10.4028/P-TM7FUN
2023-04-08 13:46:09 [INFO]  retrieve 10.4028/P-63O58D
2023-04-08 13:46:10 [INFO]  retrieve 10.5555/1860-5397-2-21
```

after a while though it fails with something like:

```
2023-04-08 14:25:01 [INFO]  retrieve 10.1007/BF02816012
Invalid language codes: ar
```

I have also seen the code de. afterwards, it isn't obvious anything was actually retrieved.

I also tried `colrev search -a /path/to/references.bib`. This loaded 77 entries and noted I should run `colrev load`. but `colrev status` suggest the next operation is `colrev retrieve`. `colrev load` is a little confusing, I get 6 options:

```
2023-04-08 15:45:37 [INFO] Discover new source: data/search/hea.bib
Select search source:
1 (confidence: 0.1): colrev.eric
2 (confidence: 0.1): colrev.ieee
3 (confidence: 0.1): colrev.jstor
4 (confidence: 0.1): colrev.psycinfo
5 (confidence: 0.1): colrev.springer_link
6 (confidence: 0.1): colrev.unknown_source
```

I chose 6 (none of the others really make sense), and then NA for the query. This led to this output:

```
2023-04-08 15:46:28 [INFO] Source name: colrev.unknown_source

2023-04-08 15:46:29 [INFO] Load data/search/pdfs.bib
2023-04-08 15:46:29 [ERROR] Did not find bib file pdfs.bib 

2023-04-08 15:46:29 [INFO] Load data/search/hea.bib
.
.
.
2023-04-08 15:46:29 [INFO]  pianassola-2023-in-situ                 md_retrieved →  md_imported
2023-04-08 15:46:29 [INFO]  pitike-2022-comput-accel                md_retrieved →  md_imported
100%|██████████████████████████████████████████████████████████████| 77/77 [00:00<00:00, 498.44it/s]
2023-04-08 15:46:29 [INFO] New records loaded                    77 records
2023-04-08 15:46:30 [INFO] Created commit

2023-04-08 15:46:30 [INFO] Completed load operation
```

Then `colrev status` indicates to run `colrev prep`, but this fails:

```
(base) Johns-iMac-4:litrev jkitchin$ colrev prep
Nothing to do (yet).
2023-04-08 15:50:20 [INFO] Prep
2023-04-08 15:50:20 [INFO] Prep completes and corrects record metadata based on APIs and preparation rules.
2023-04-08 15:50:20 [INFO] See https://colrev.readthedocs.io/en/latest/manual/metadata_retrieval/prep.html
2023-04-08 15:50:23 [INFO] Info: The language detector requires RAM and may take longer
Traceback (most recent call last):
  File "/Users/jkitchin/opt/anaconda3/bin/colrev", line 8, in <module>
    sys.exit(main())
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 828, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 781, in main
    rv = self.invoke(ctx)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1227, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1046, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 590, in invoke
    return callback(*args, **kwargs)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/colrev/ui_cli/cli.py", line 628, in prep
    prep_operation.main(keep_ids=keep_ids, cpu=cpu, polish=polish)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/colrev/ops/prep.py", line 982, in main
    prepared_records = pool.map(self.prepare, preparation_data)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/colrev/ops/prep.py", line 259, in prepare
    preparation_record = endpoint.prepare(self, preparation_record)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/timeout_decorator/timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/site-packages/timeout_decorator/timeout_decorator.py", line 147, in __call__
    self.__process.start()
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/jkitchin/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function SourceSpecificPrep.prepare at 0x7ff350f44f70>: it's not the same object as colrev.ops.built_in.prep.source_specific_prep.SourceSpecificPrep.prepare
```

I assume this is a bug.

anyway, I am kind of stuck at this point. My current repo has this status.

```
Nothing to do (yet).
Status
    init 
    retrieve          0 retrieved     77 to prepare 
    prescreen         0 included      
    pdfs              0 retrieved     
    screen            0 included      
    data              0 synthesized   

Next operation
    colrev prep

CoLRev environment

  Search and download curated metadata for your project (if available). 
  The most common journals in your project are 
   - CoRR (8.0%).
  They may be available at https://github.com/CoLRev-curations

For more details: colrev status -v
```

**Comment by geritwagner** [comment]
Thank you for the overview. I have just pushed updates related to the crossref search and language codes. Hopefully, the search is completed successfully with these changes. I assume you did not use the exact query ("microsourcing") because the DOI metadata does not match the keyword.

Can I ask what the original source of the 77 entries is? In cases where the SearchSource is not detected (i.e., low confidence values for all candidates), we could consider selecting the unknown_source per default. I assume that would be less confusing?

Concerning the PicklingError: This is a bug we did not encounter before. Could you check whether it is a bug of source_specific_prep by removing the "colrev.source_specific_prep" entry from settings.json, committing it, and rerunning colrev prep?

**Comment by jkitchin** [comment]
I did use exactly `colrev search -a colrev.crossref:"https://search.crossref.org/?q=+microsourcing&from_ui=yes"`.

I pulled the new repo. It seems the repo does not work with numpy 1.24.2, and I had to downgrade it to 1.23.5

The last error I got was
```
from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```
it works fine with 1.23.5

The 77 entries came from a bibtex file I have curated for a while from various sources, e.g. from journal TOCs, arxiv, mostly, on the topic of high entropy alloys.

It seems like I am having trouble committing the change to settings.json, it seems stuck on

CoLRev ReviewManager: report.............................................

I can't seem to skip this with --no-verify either...

**Comment by jkitchin** [comment]
I started a new repo, and now the search command `colrev search -a colrev.crossref:"https://search.crossref.org/?q=+microsourcing&from_ui=yes"` retrieved only 6 references, and the do seem related to microsourcing.

**Comment by geritwagner** [comment]
I'm glad that the crossref search now works as expected. The numpy issue seems to be a recent bug that should be fixed in the original library. For the 77 entries, the "unknown_source" should be correct, as they don't belong to a single SearchSource.

The PicklingError may be a Mac-specific bug in the multiprocessing-setup. I do not have a Mac at hand to reproduce the issue. It does not occur on my Linux machine/the tests on GitHub actions. The matrix tests for different platforms will hopefully be completed in a few days (see #147). Additional details that could help to resolve the PicklingError would be much appreciated. As a workaround, the [loop in colrev/ops/prep.py](https://github.com/CoLRev-Environment/colrev/blob/main/colrev/ops/prep.py#L966) should not lead to multiprocessing/pickling issues.

**Comment by geritwagner** [comment]
A quick update: I could not reproduce the PicklingError. One option would be to switch to pathos (dill), which seems to handle pickling more comprehensively than the built-in multiprocessing. In the meantime, ``colrev prep --cpu 1`` should help to avoid any multiprocessing-related issues.

**Comment by geritwagner** [comment]
The tests on mac are now fully passing. Is the error still raised with the current version/does the `colrev prep --cpu 1` solve the issue?

**Comment by jkitchin** [comment]
I tried updating to Python 3.10. `colrev prep` did work, without --cpu 1. 

but I still have this problem with a current pull on colrev in `colrev retrieve`:

```
  File "/Users/jkitchin/anaconda3/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function CrossrefSearchSource.__run_parameter_search at 0x7fb7d8aa3640>: attribute lookup CrossrefSearchSource.__run_parameter_search on colrev.ops.built_in.search_sources.crossref failed
```

I will also note I see a numba error with numpy>1.23.5, and I had to downgrade to 1.23.5 to get it to work.

**Comment by geritwagner** [comment]
Ok, the Pickling-error may be related to the timeout_decorators (which apparently have limited cross-platform compatibility). I replaced them in the last commit, hoping that it resolves the issue.

**Comment by jkitchin** [comment]
This seems to have resolved it for me. I think we can close this for now.

**Comment by geritwagner** [comment]
Great! Thank you for sharing the bug-reports and confirming the issue resolution.
